# Generated by Django 4.1.2 on 2022-12-24 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 12, 24, 9, 8, 21, 439298))),
            ],
        ),
    ]
